version: "3.7"

services:

  mysql:
    image: mysql:5.7
    platform: linux/amd64
    hostname: mysql
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: baas-core-database
      MYSQL_ROOT_PASSWORD: baas-core-database
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
